ros_node:
  loop_rate: 120.0

# defining up to 4 robots
robots:

  robot_1:
    name: franka_1
    frame_id:
    motion_interface_idndex: 1
    topics:
      ee_pose:
      desired_motions:
      motion_interface: /mocap_system/pose_arrays
    T_RM:
      rotation:
        - [1, 0, 0]
        - [0, 1, 0]
        - [0, 0, 1]
      translation: [0, 0, 0]

  robot_2:
    name: 
    frame_id:
    motion_interface_idndex: 2
    topics:
      ee_pose:
      desired_motions: 
      motion_interface:
    T_RM:
      rotation:
        - [1, 0, 0]
        - [0, 1, 0]
        - [0, 0, 1]
      translation: [0, 0, 0]

  robot_3:
    name:
    frame_id: 
    motion_interface_idndex: 3
    topics:
      ee_pose:
      desired_motions:
      motion_interface:
    T_RM:
      rotation:
        - [1, 0, 0]
        - [0, 1, 0]
        - [0, 0, 1]
      translation: [0, 0, 0]

  robot_4:
    name:
    frame_id:
    motion_interface_idndex: 4
    topics:
      ee_pose:
      desired_motions:
      motion_interface:
    T_RM:
      rotation:
        - [1, 0, 0]
        - [0, 1, 0]
        - [0, 0, 1]
      translation: [0, 0, 0]
